import { NextRequest, NextResponse } from 'next/server';
import { getAdminFromRequest, isSuperAdmin } from '@/lib/auth';
import { supabaseAdmin as supabase } from '@/lib/supabase';

const REFUND_STATUSES = new Set(['pending', 'reviewing', 'approved', 'processing', 'completed', 'rejected']);

const CREATE_REFUND_TABLE_SQL = `
  create table if not exists public.refund_requests (
    id bigint generated by default as identity primary key,
    request_code text not null unique
      constraint refund_requests_code_check
      check (request_code ~ '^RF-[0-9]{8}-[A-F0-9]{8}$'),
    order_id bigint not null unique references public.orders(id) on delete restrict,
    buyer_id bigint not null references public.buyers(id) on delete restrict,
    refund_amount numeric(14, 2) not null
      constraint refund_requests_amount_check check (refund_amount >= 0),
    ewallet_provider text not null
      constraint refund_requests_provider_check check (ewallet_provider in ('dana', 'gopay')),
    ewallet_number text not null
      constraint refund_requests_number_check check (ewallet_number ~ '^[0-9]{9,15}$'),
    account_holder_name text not null
      constraint refund_requests_holder_check check (char_length(btrim(account_holder_name)) between 2 and 100),
    status text not null default 'pending'
      constraint refund_requests_status_check
      check (status in ('pending', 'reviewing', 'approved', 'processing', 'completed', 'rejected')),
    admin_notes text,
    processed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  );

  create index if not exists refund_requests_buyer_id_idx
    on public.refund_requests (buyer_id);
  create index if not exists refund_requests_status_created_idx
    on public.refund_requests (status, created_at desc);

  alter table public.refund_requests enable row level security;
  revoke all on table public.refund_requests from public, anon, authenticated;
  grant select, insert, update, delete on table public.refund_requests to service_role;
  grant usage, select on sequence public.refund_requests_id_seq to service_role;
  notify pgrst, 'reload schema';
`;

function normalizeText(value: unknown, maxLength: number) {
  return typeof value === 'string' ? value.trim().slice(0, maxLength) : '';
}

export async function GET(request: NextRequest) {
  if (!(await getAdminFromRequest(request))) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const status = new URL(request.url).searchParams.get('status');
  if (status && status !== 'all' && !REFUND_STATUSES.has(status)) {
    return NextResponse.json({ error: 'Filter status tidak valid.' }, { status: 400 });
  }

  let query = supabase
    .from('refund_requests')
    .select(`
      *,
      orders (
        order_number,
        total_amount,
        order_status,
        payment_status,
        buyer:buyers (name, email, phone),
        product:products (name, code)
      )
    `)
    .order('created_at', { ascending: false });

  if (status && status !== 'all') query = query.eq('status', status);

  const { data, error } = await query;
  if (error) return NextResponse.json({ error: 'Gagal memuat pengajuan refund.' }, { status: 400 });
  return NextResponse.json(data || []);
}

export async function POST(request: NextRequest) {
  const admin = await getAdminFromRequest(request);
  if (!admin) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  if (!isSuperAdmin(admin)) return NextResponse.json({ error: 'Hanya superadmin yang dapat menyiapkan database refund.' }, { status: 403 });

  const { error: migrationError } = await supabase.rpc('exec_sql', { sql: CREATE_REFUND_TABLE_SQL });
  if (migrationError) {
    console.error('Refund migration error:', migrationError.message);
    return NextResponse.json({ error: 'Migrasi otomatis gagal. Jalankan file migrasi refund melalui Supabase SQL Editor.' }, { status: 500 });
  }

  const { error: verificationError } = await supabase
    .from('refund_requests')
    .select('id', { count: 'exact', head: true });
  if (verificationError) {
    console.error('Refund migration verification error:', verificationError.message);
    return NextResponse.json({ error: 'Tabel dibuat, tetapi belum dapat dibaca. Muat ulang halaman beberapa saat lagi.' }, { status: 500 });
  }

  return NextResponse.json({ success: true, message: 'Database refund berhasil disiapkan.' });
}

export async function PUT(request: NextRequest) {
  const admin = await getAdminFromRequest(request);
  if (!admin) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    const body = await request.json();
    const id = Number(body.id);
    const status = normalizeText(body.status, 30);
    const adminNotes = normalizeText(body.admin_notes, 2000);

    if (!Number.isSafeInteger(id) || id <= 0) {
      return NextResponse.json({ error: 'ID pengajuan tidak valid.' }, { status: 400 });
    }
    if (!REFUND_STATUSES.has(status)) {
      return NextResponse.json({ error: 'Status refund tidak valid.' }, { status: 400 });
    }

    const { data: previous, error: previousError } = await supabase
      .from('refund_requests')
      .select('*')
      .eq('id', id)
      .single();
    if (previousError || !previous) {
      return NextResponse.json({ error: 'Pengajuan refund tidak ditemukan.' }, { status: 404 });
    }

    const { data, error } = await supabase
      .from('refund_requests')
      .update({
        status,
        admin_notes: adminNotes || null,
        processed_at: status === 'completed' ? new Date().toISOString() : null,
        updated_at: new Date().toISOString(),
      })
      .eq('id', id)
      .select()
      .single();

    if (error) return NextResponse.json({ error: 'Gagal memperbarui status refund.' }, { status: 400 });

    const { error: auditError } = await supabase.from('audit_logs').insert({
      admin_id: admin.id,
      actor_type: 'admin',
      action: 'update_refund_request',
      entity_type: 'refund_request',
      entity_id: id,
      before_data: previous,
      after_data: data,
    });
    if (auditError) console.error('Failed to write refund audit log:', auditError.message);

    return NextResponse.json(data);
  } catch (error) {
    console.error('Admin refund update error:', error);
    return NextResponse.json({ error: 'Terjadi kesalahan saat memperbarui refund.' }, { status: 500 });
  }
}
