begin;

create table public.refund_requests (
  id bigint generated by default as identity primary key,
  request_code text not null unique
    constraint refund_requests_code_check
    check (request_code ~ '^RF-[0-9]{8}-[A-F0-9]{8}$'),
  order_id bigint not null unique
    references public.orders(id) on delete restrict,
  buyer_id bigint not null
    references public.buyers(id) on delete restrict,
  refund_amount numeric(14, 2) not null
    constraint refund_requests_amount_check check (refund_amount >= 0),
  ewallet_provider text not null
    constraint refund_requests_provider_check check (ewallet_provider in ('dana', 'gopay')),
  ewallet_number text not null
    constraint refund_requests_number_check check (ewallet_number ~ '^[0-9]{9,15}$'),
  account_holder_name text not null
    constraint refund_requests_holder_check check (char_length(btrim(account_holder_name)) between 2 and 100),
  status text not null default 'pending'
    constraint refund_requests_status_check
    check (status in ('pending', 'reviewing', 'approved', 'processing', 'completed', 'rejected')),
  admin_notes text,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index refund_requests_buyer_id_idx
  on public.refund_requests (buyer_id);

create index refund_requests_status_created_idx
  on public.refund_requests (status, created_at desc);

alter table public.refund_requests enable row level security;

revoke all on table public.refund_requests from public, anon, authenticated;
grant select, insert, update, delete on table public.refund_requests to service_role;
grant usage, select on sequence public.refund_requests_id_seq to service_role;

commit;
