create table if not exists public.reseller_login_attempts (
  id bigint generated by default as identity primary key,
  ref_code text not null check (char_length(ref_code) between 1 and 32),
  ip_address text not null check (char_length(ip_address) between 1 and 128),
  attempted_at timestamptz not null default now()
);

alter table public.reseller_login_attempts enable row level security;

revoke all on table public.reseller_login_attempts from anon, authenticated;
grant select, insert, delete on table public.reseller_login_attempts to service_role;
grant usage, select on sequence public.reseller_login_attempts_id_seq to service_role;

create index if not exists reseller_login_attempts_ref_code_attempted_at_idx
  on public.reseller_login_attempts (ref_code, attempted_at desc);

create index if not exists reseller_login_attempts_ref_code_ip_address_idx
  on public.reseller_login_attempts (ref_code, ip_address);

create index if not exists reseller_login_attempts_attempted_at_idx
  on public.reseller_login_attempts (attempted_at);

comment on table public.reseller_login_attempts is
  'Server-only failed reseller login attempts used for brute-force protection.';
