create table public.buyer_ban_identifiers (
  id bigint generated by default as identity primary key,
  buyer_id bigint not null references public.buyers(id) on delete cascade,
  identifier_type text not null
    constraint buyer_ban_identifiers_type_check
    check (identifier_type in ('email', 'phone', 'ip')),
  identifier_hash text not null
    constraint buyer_ban_identifiers_hash_check
    check (identifier_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  constraint buyer_ban_identifiers_unique
    unique (buyer_id, identifier_type, identifier_hash)
);

create index buyer_ban_identifiers_hash_idx
  on public.buyer_ban_identifiers (identifier_hash);

create index buyer_ban_identifiers_buyer_idx
  on public.buyer_ban_identifiers (buyer_id);

alter table public.buyer_ban_identifiers enable row level security;

revoke all on table public.buyer_ban_identifiers from public, anon, authenticated;
grant select, insert, update, delete on table public.buyer_ban_identifiers to service_role;
grant usage, select on sequence public.buyer_ban_identifiers_id_seq to service_role;

create or replace function public.set_buyer_ban(
  p_buyer_id bigint,
  p_banned boolean,
  p_identifiers jsonb default '[]'::jsonb
)
returns table(status text, identifiers_count bigint)
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if p_banned then
    update public.buyers
    set status = 'blocked', updated_at = now()
    where id = p_buyer_id;
  else
    update public.buyers
    set status = 'active', updated_at = now()
    where id = p_buyer_id;
  end if;

  if not found then
    raise exception 'Buyer not found';
  end if;

  if p_banned then
    insert into public.buyer_ban_identifiers (
      buyer_id,
      identifier_type,
      identifier_hash
    )
    select
      p_buyer_id,
      item->>'type',
      item->>'hash'
    from jsonb_array_elements(p_identifiers) as item
    where item->>'type' in ('email', 'phone', 'ip')
      and item->>'hash' ~ '^[0-9a-f]{64}$'
    on conflict (buyer_id, identifier_type, identifier_hash) do nothing;
  else
    delete from public.buyer_ban_identifiers
    where buyer_id = p_buyer_id;
  end if;

  return query
  select
    case when p_banned then 'blocked' else 'active' end::text,
    count(*)::bigint
  from public.buyer_ban_identifiers
  where buyer_id = p_buyer_id;
end;
$$;

revoke all on function public.set_buyer_ban(bigint, boolean, jsonb)
  from public, anon, authenticated;
grant execute on function public.set_buyer_ban(bigint, boolean, jsonb)
  to service_role;

